# gslb2.zerodns.co.uk. secondary / replica node
listen_addrs:
  - "[2a02:8012:bc57:53a::1]:53"

timeout_sec: 5
interval_sec: 8
rise: 2
fall: 4
jitter_ms: 200
cooldown_sec: 25
edns_buf: 1232
log_queries: true
log_syslog: false

tsig:
  path: "/etc/breathgslb/tsig"

discovery:
  catalog_zone: "_catalog.breathgslb."
  masters:
    - "[2a02:8012:bc57:53::1]:53"
  xfr_source: "2a02:8012:bc57:53a::1"
  tsig:
    default_algorithm: "hmac-sha256"
    keys:
      - name: "lightitup-xfr."
        secret: ""

geoip:
  enabled: true
  database: "/etc/breathgslb/geoip/GeoLite2-Country.mmdb"
  prefer_field: "country"
  cache_ttl_sec: 600
