listen_addrs:
  - "[2a02:8012:bc57:53::1]:53"
  - "[2a02:8012:bc57:5353::1]:53"
zones_dir: "/etc/breathgslb/zones"
reverse_dir: "/etc/breathgslb/reverse"

timeout_sec: 5
interval_sec: 8
rise: 2
fall: 4
jitter_ms: 200
cooldown_sec: 25
edns_buf: 1232
log_queries: true
log_syslog: false

api: true
api-listen: 9443
api-token: "/etc/breathgslb/api.token"
api-cert: "/etc/breathgslb/api.crt"
api-key: "/etc/breathgslb/api.key"

tsig:
  path: "/etc/breathgslb/tsig"

discovery:
  catalog_zone: "_catalog.breathgslb."
  ttl: 60
  tsig:
    default_algorithm: "hmac-sha256"
    keys:
      - name: "lightitup-xfr."
        secret: ""
        allow_xfr_from:
          - "::1"
          - "127.0.0.1"
          - "2a02:8012:bc57:53a::/64"

geoip:
  enabled: true
  database: "/etc/breathgslb/geoip/GeoLite2-Country.mmdb"
  prefer_field: "country"
  cache_ttl_sec: 600
