listen_addrs:
  - "[2a02:8012:bc57:53::1]:53"
  - "[2a02:8012:bc57:5353::1]:53"
zones_dir: "/etc/breathgslb/zones"
reverse_dir: "/etc/breathgslb/reverse"

timeout_sec: 5
interval_sec: 8
rise: 2
fall: 4
jitter_ms: 200
cooldown_sec: 25
edns_buf: 1232
log_queries: true
log_syslog: false

tsig:
  path: "/etc/breathgslb/tsig"

geoip:
  enabled: true
  database: "/etc/breathgslb/geoip/GeoLite2-Country.mmdb"
  prefer_field: "country"
  cache_ttl_sec: 600


