db:
  driver: sqlite
  dsn: web.db
admin:
  email: admin@example.com
  password_hash: "$2a$10$UakOiKAu3PG9.7nJzLqRKe0sHlxHeHUB7UK7Y/wKvJ5ScJf9WX4Zi"
server:
  interface: "" # network interface to bind (optional)
  port: 8080
  ip: ""       # explicit IP to bind (optional)
email:
  mode: smtp # or "gmail"
  smtp:
    server: smtp.example.com:587
    username: user@example.com
    password: secret
    from: noreply@example.com
