db:
  driver: sqlite
  dsn: web.db
admin:
  email: admin@example.com
  password_hash: "$2a$10$UakOiKAu3PG9.7nJzLqRKe0sHlxHeHUB7UK7Y/wKvJ5ScJf9WX4Zi"
server:
  interface: ""
  port: 8080
  ip: ""
public_signup: true
